import { persistStore } from 'redux-persist'
import '../styles/globals.scss'
import { Provider } from 'react-redux';
import store from '../store';
import Head from 'next/head'
import { PersistGate } from 'redux-persist/integration/react';

let persistor = persistStore(store);
function MyApp({ Component, pageProps }) {
  return (

    <>
      <Head>
        <title>My Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        < Component {...pageProps} />
      </PersistGate>
    </Provider>
    </>
    
  )


}

export default MyApp
